# monkey man into the dandiverse
(upload the latest version of the dataset to dandi)

## first validate the data
run "run_nwb_validator.bat"

## then inspect data

In [ ]:
from nwbinspector import inspect_all
# where is the data
dataset_path = "Z:\\Student Folders\\Nina_Gill\\data\\nwb_out"

all_results = list(inspect_all(path=dataset_path))

In [ ]:
import pkl_to_nwb
import config
import pickle
import os
import numpy as np

(nwb_converted_CO, nwb_converted_RD) = pkl_to_nwb.dicts_from_pickle(
    f"{config.good_daysdir}/2020-01-27_CO.nwb",
    config.nwbdir,
)

with open(os.path.join(config.good_daysdir, '2020-01-27_preprocess.pkl'), 'rb') as f:
    original_CO, original_RD = pickle.load(f)

#make sure they have the same keys
assert(original_CO.keys() == nwb_converted_CO.keys())

for key in original_CO.keys():
    new_data = nwb_converted_CO[key]
    old_data = original_CO[key]

    if hasattr(new_data, "__len__"):
        try:
            if type(new_data) == np.ndarray:
                assert((new_data==old_data).all())
            else:
                assert(new_data == old_data)
        except:
            print(key)
            print(new_data.dtype)
            print(old_data.dtype)
    else:
        try:
            assert(old_data == new_data)
        except:
            print("NEW DATA: \n")
            print(new_data)
            print("OLD DATA: \n")
            print(old_data)

time
[  8410   8430   8450 ... 561330 561350 561370]
[  8410   8430   8450 ... 561330 561350 561370]
finger_kinematics
[[ 4.9897426e-01  5.4876542e-01  2.5641322e-03  0.0000000e+00]
 [ 5.0153840e-01  5.4876542e-01 -2.8204322e-03  7.4070692e-04]
 [ 4.9871796e-01  5.4950613e-01  2.0512938e-03 -3.7032366e-04]
 ...
 [ 8.6897439e-01  4.5320982e-01 -3.0769110e-03 -4.9379468e-04]
 [ 8.6589748e-01  4.5271602e-01  7.6919794e-04 -7.4073672e-04]
 [ 8.6666667e-01  4.5197529e-01  0.0000000e+00  0.0000000e+00]]
[[ 4.98974264e-01  5.48765421e-01  2.56413221e-03  0.00000000e+00]
 [ 5.01538396e-01  5.48765421e-01 -2.82043219e-03  7.40706921e-04]
 [ 4.98717964e-01  5.49506128e-01  2.05129385e-03 -3.70323658e-04]
 ...
 [ 8.68974388e-01  4.53209817e-01 -3.07691097e-03 -4.93794680e-04]
 [ 8.65897477e-01  4.52716023e-01  7.69197941e-04 -7.40736723e-04]
 [ 8.66666675e-01  4.51975286e-01  0.00000000e+00  0.00000000e+00]]


In [ ]:
nwb_to =data_co['time']
bb = data_co1['time']

print(aa[aa>=16130])
print(bb[aa>=16130])


[ 16130  16150  16170 ... 561330 561350 561370]
[ 16129  16149  16170 ... 561330 561350 561370]
